groups:
  - name: rtap_alerts
    rules:
      # Service health alerts
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute"

      # RTSP Server alerts
      - alert: HighStreamFailureRate
        expr: rate(rtsp_stream_failures_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High stream failure rate"
          description: "Stream failures rate is above 10% in the last 5 minutes"

      - alert: StreamLatencyHigh
        expr: rtsp_stream_latency_seconds > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High stream latency"
          description: "Stream latency is above 2 seconds for more than 5 minutes"

      # Annotation Service alerts
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate on {{ $labels.job }}"
          description: "Error rate is above 10% in the last 5 minutes"

      - alert: HighResponseTime
        expr: http_request_duration_seconds{quantile="0.9"} > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time on {{ $labels.job }}"
          description: "90th percentile of response time is above 1 second"

      # MongoDB alerts
      - alert: MongoDBHighConnections
        expr: mongodb_connections{state="current"} > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High number of MongoDB connections"
          description: "MongoDB has more than 1000 connections"

      # Redis alerts
      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Redis high memory usage"
          description: "Redis memory usage is above 80%"

      # System alerts
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 80%"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is above 80%"

      - alert: DiskSpaceRunningOut
        expr: node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} * 100 < 20
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space on {{ $labels.instance }}"
          description: "Disk space is below 20%"
