global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rtsp_server'
    static_configs:
      - targets: ['rtsp-server:8554']

  - job_name: 'annotation_service'
    static_configs:
      - targets: ['annotation-service:3000']

  - job_name: 'nginx'
    static_configs:
      - targets: ['api-gateway:80']

rule_files:
  - 'alert.rules.yml'
